apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: blackhole
  labels:
    app: ui
    app.kubernetes.io/name: ui
    app.kubernetes.io/part-of: blackhole
spec:
  type: NodePort
  selector:
    app: ui
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
