services:
  ui:
    build:
      context: ..
      dockerfile: services/ui-static/Dockerfile
    image: bh/ui:dev
    ports: ["8080:80"]
    depends_on: [ray-api, blackhole-api]
  ray-api:
    build:
      context: ..
      dockerfile: services/ray-api/Dockerfile
    image: bh/ray-api:dev
    ports: ["8000:8000"]
    depends_on: [redis]

  blackhole-api:
    build:
      context: ..
      dockerfile: services/blackhole-api/Dockerfile
    image: bh/blackhole-api:dev
    ports: ["8001:8001"]

  worker:
    build:
      context: ..
      dockerfile: services/worker/Dockerfile
    image: bh/worker:dev
    depends_on: [redis]
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_BACKEND_URL: redis://redis:6379/1

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
