[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "core-physics"
version = "0.1.0"
description = "Core GR physics for blackhole sim"
requires-python = ">=3.10"

[tool.setuptools]
packages = ["core_physics"]
